---
version: 3

images:
  base_image:
    name: rockylinux/rockylinux:9

options:
  package_manager_path: /usr/bin/microdnf
  build_arg_defaults:
    PYCMD: /usr/bin/python3.11

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.16.0,<2.17
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: amazon.aws
      - name: ansible.posix
      - name: ansible.windows
      - name: awx.awx
      - name: azure.azcollection
      - name: community.windows
      - name: community.vmware
      - name: kubernetes.core
      - name: google.cloud
      - name: openstack.cloud
      - name: ovirt.ovirt
      - name: theforeman.foreman
      - name: vultr.cloud
      - name: community.libvirt
      - name: community.proxmox
  system:
    - epel-release [platform:rpm]
    - gcc [platform:rpm]
    - git [platform:rpm]
    - krb5-devel [platform:rpm]
    - python3.11-devel [platform:rpm compile]
    - python3.11-pip [platform:rpm]
    - python3.11-setuptools [platform:rpm]
    - sshpass [platform:rpm]
    - podman-remote [platform:rpm]
    - google-cloud-cli [platform:rpm]
  python:
    - ansible-sign
    - ncclient
    - paramiko
    - pexpect
    - pywinrm
    - boto3
    - proxmoxer
    - google-auth

additional_build_steps:
  append_base:
    - ADD _build/configs/sudoers /etc/sudoers.d/ascender
    - RUN chmod 0440 /etc/sudoers.d/ascender
    - ADD _build/configs/google-cloud-cli.repo /etc/yum.repos.d/google-cloud-cli.repo
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN mkdir -p /runner
    - RUN useradd -u 1000 -m ascender
    - RUN chown -R ascender:ascender /runner
    - RUN chown -R ascender:ascender /var/run/receptor
    - RUN chmod 0777 /runner
    - RUN chmod 0777 /var/run/receptor
    - RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.11 1
    - RUN ln -sf /usr/bin/python3.11 /usr/bin/python3
    - RUN ln -sf /usr/bin/python3.11 /usr/bin/python
