---
version: 3

images:
  base_image:
    name: rockylinux/rockylinux:9-minimal

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core>=2.16.14,<2.17
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: amazon.aws
      - name: ansible.posix
      - name: ansible.windows
      - name: awx.awx
      - name: azure.azcollection
      - name: community.windows
      - name: community.vmware
      - name: kubernetes.core
      - name: google.cloud
      - name: openstack.cloud
      - name: ovirt.ovirt
      - name: theforeman.foreman
      - name: vultr.cloud
      - name: community.libvirt
      - name: community.proxmox
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pexpect
    pywinrm
    boto3
    proxmoxer
    google-auth
  system: |
    crypto-policies-scripts
    epel-release [platform:rpm]
    gcc [platform:rpm]
    gcc-c++ [platform:rpm]
    git-core [platform:rpm]
    git-lfs [platform:rpm]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    libcurl-devel [platform:rpm compile]
    podman-remote [platform:rpm]
    python3.11-devel [platform:rpm compile]
    rsync [platform:rpm]
    sshpass [platform:rpm]
    subversion [platform:dpkg]
    subversion [platform:rpm]
    unzip [platform:rpm]
    sudo [platform:rpm]
    libxcrypt-compat.x86_64 [platform:rpm]
    google-cloud-cli [platform:rpm]

additional_build_files:
  - src: includes/sudoers
    dest: configs
  - src: includes/google-cloud-cli.repo
    dest: configs

additional_build_steps:
  prepend_base:
    - ADD _build/configs/google-cloud-cli.repo /etc/yum.repos.d/google-cloud-cli.repo
    - RUN microdnf -y install google-cloud-cli
  prepend_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /etc/receptor
  append_final:
    - COPY _build/configs/sudoers /etc/sudoers.d/ascender
    - RUN chmod 0440 /etc/sudoers.d/ascender
    - RUN mkdir -p /runner && chown 1000:1000 /runner && chmod 0750 /runner
    - RUN useradd -u 1000 -m -s /bin/bash ascender
    - RUN echo "ascender ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    - RUN microdnf update -y && microdnf clean all
