[tox]
envlist = ee

[gh-actions]
python = 3.9
    ee

[testenv]
allowlist_externals =
    /bin/bash
    /usr/bin/cp
    /usr/bin/rm
commands =
    ansible-builder build -v3 -t ghcr.io/{envowner}/main-ee:{posargs} -f execution-environment.yml
