---
name: Build latest image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-2-15:
    name: Build Ansible 2.15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder
      - name: Build and Push EE 2.15
        run: |
          docker rmi ghcr.io/ssimpson89/main-ee:dev-2.15 2>/dev/null || true
          ansible-builder build -v3 -t ghcr.io/ssimpson89/main-ee:dev-2.15 --container-runtime=docker -f execution-environment-2.15.yml
          docker push ghcr.io/ssimpson89/main-ee:dev-2.15

  build-2-16:
    name: Build Ansible 2.16
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder
      - name: Build and Push EE 2.16
        run: |
          docker rmi ghcr.io/ssimpson89/main-ee:dev 2>/dev/null || true
          ansible-builder build -v3 -t ghcr.io/ssimpson89/main-ee:dev --container-runtime=docker -f execution-environment.yml
          docker push ghcr.io/ssimpson89/main-ee:dev
