---
name: Release

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

concurrency:
  group: release-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version_tag: ${{ github.event.release.tag_name }}
      moving_tag: latest
